version: '3.8'

# имя директории для хранения данных
volumes:
  postgres_data:
  staticfiles:

# имена и описания контейнеров, которые должны быть развёрнуты
services:
  # описание контейнера db
  db:
    # образ, из которого должен быть запущен контейнер
    image: postgres:12.4
    # volume и связанная с ним директория в контейнере
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    # адрес файла, где хранятся переменные окружения
    env_file:
      - ./.env
  web:
    image: johncway/yamdb:latest
    restart: always
    volumes:
      - staticfiles:/code/static
    # "зависит от", 
    depends_on:
      - db
    env_file:
      - ./.env 

  nginx:
    build: ./nginx
    restart: always
    volumes:
      - staticfiles:/static
    ports:
      - "8080:8080"
    depends_on:
      - web