# Generated by Django 3.1.2 on 2020-10-30 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20201026_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag', to='recipes.recipe'),
        ),
    ]
