# Generated by Django 3.1.2 on 2020-11-02 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20201102_0725'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='measurement_unit',
            new_name='dimension',
        ),
    ]
